### ISSUE TITLE
Drop gocheck dependency

### ISSUE THREAD

**Issue by magiconair** [magiconair/properties#15]
It is not necessary and makes Debian packaging more complex since they unbundle the vendored dependencies.

**Comment by magiconair** [comment]
That's merged to master now.

**Comment by anthonyfok** [comment]
> As a result of [the] discussion [in #14] I've removed the dependency on gopkg.in/gocheck.v1 in #15 which is in v1.7.1 and later.
>
> It is not necessary and makes Debian packaging more complex since they unbundle the vendored dependencies.

Wow, that is a rather drastic change!  Though as the initial packager of the golang-github-magiconair-properties package in Debian, I can assure you that it is no extra burden on us at all, especially when many other Go packages use vendoring and we deal with those the same way too.

Nevertheless, thank you for being so thoughtful and accommodating to us Debian Developers!
But yes, in case you ever wanted to add gocheck back, or to re-introduce vendoring, please feel free to do so any time, and I would be happy to adjust the packaging accordingly.  :-)

(After reading the discussions at #14, I think I am more pragmatic than philosophical...)

Thanks again, and cheers!  :-)
