### ISSUE TITLE
Maintain order of key with FilterXXX

### ISSUE THREAD

**Issue by dotwilbert** [magiconair/properties#4]
Hi all,

Thanks for sharing your work. I find your package very useful. My properties files must also be edited by administrators. In my program I remove program generated properties and rewrite the properties file. Maintaining the order of the keys and the comments enables a friendlier file for administrators. The comments are transferred using GetComments. I could not find another way to keep the unexpanded property values, except by filtering them.

Currently the order of the keys is not maintained when any of the Filter, FilterRegexp or FilterPrefix is called. A small set of changes in properties.go will enable this.
``` Go
  // FilterRegexp returns a new properties object which contains all properties
  // for which the key matches the regular expression.
  func (p *Properties) FilterRegexp(re *regexp.Regexp) *Properties {
  	pp := NewProperties()
  //for k, v := range p.m {
  	for _, k := range p.k {
  		if re.MatchString(k) {
  //		pp.Set(k, v)
  			pp.Set(k, p.m[k])
  		}
  	}
  	return pp
  }

  // FilterPrefix returns a new properties object which contains all properties
  // for which the key starts with the prefix.
  func (p *Properties) FilterPrefix(prefix string) *Properties {
  	pp := NewProperties()
  //for k, v := range p.m {
  	for _, k := range p.k {
  		if strings.HasPrefix(k, prefix) {
  //		pp.Set(k, v)
  			pp.Set(k, p.m[k])
  		}
  	}
  	return pp
  }
```

Thanks,

Wilbert

**Comment by magiconair** [comment]
Thanks Wilbert for finding this. I've added your change and tagged version v1.5.3 with it.
