### ISSUE TITLE
Bug(writeComments): Changes comments if \ is included

### ISSUE THREAD

**Issue by doxsch** [magiconair/properties#54]
When reading comments `\` are loaded correctly, but when writing they are then replaced by `\\`. This leads to wrong comments when writing and reading multiple times.

I assume that it is not necessary to encode the comments.

**Comment by doxsch** [comment]
Hi @magiconair 

Thanks for merging my changes. Would it be possible to release a new version (v1.8.5)? 

Best regards doxsch

**Comment by magiconair** [comment]
Fixing tests for older versions now. Then I'll tag. Version parsing was not quite right.

**Comment by magiconair** [comment]
Tagged.

**Comment by doxsch** [comment]
Thanks
