### ISSUE TITLE
Test failure on 32-bit platforms: "constant 4294967296 overflows int"

### ISSUE THREAD

**Issue by anthonyfok** [magiconair/properties#7]
Detected on armhf by a Debian reproducible build server here:

https://reproducible.debian.net/rb-pkg/unstable/armhf/golang-github-magiconair-properties.html

```
go test -v github.com/magiconair/properties
# github.com/magiconair/properties
src/github.com/magiconair/properties/properties_test.go:811: constant 4294967296 overflows int
FAIL	github.com/magiconair/properties [build failed]
```

This happens inside `TestPanicOn32BitUintOverflow()`:

https://github.com/magiconair/properties/blob/master/properties_test.go#L811

This test fails on 32-bit platforms such as armhf, but works fine with 64-bit platforms such as amd64.

Thanks in advance!

Anthony

**Comment by anthonyfok** [comment]
Detected on armhf by a Debian reproducible build server here:

https://reproducible.debian.net/rb-pkg/unstable/armhf/golang-github-magiconair-properties.html

```
go test -v github.com/magiconair/properties
# github.com/magiconair/properties
src/github.com/magiconair/properties/properties_test.go:811: constant 4294967296 overflows int
FAIL	github.com/magiconair/properties [build failed]
```

The relevant code is here:

https://github.com/magiconair/properties/blob/master/properties_test.go#L811

Thanks in advance!

Anthony

**Comment by magiconair** [comment]
This should fix it. Please let me know if it does not. Thx for reporting.

**Comment by anthonyfok** [comment]
Thank you very much for your prompt response and fix!

I am just responding back to tell you that your fix works perfectly, as seen in the just-completed (20 minutes ago) Debian reproducible build log on armhf below:

https://reproducible.debian.net/rbuild/unstable/armhf/golang-github-magiconair-properties_1.6.0-2.rbuild.log

Cheers, and Merry Christmas!

Anthony
