### ISSUE TITLE
GetInt should return default val instead of panic

### ISSUE THREAD

**Issue by FarmerChillax** [magiconair/properties#75]
In `GetInt` function should return default value instead of panic

```
// GetInt parses the expanded value as an int if the key exists.
// If key does not exist or the value cannot be parsed the default
// value is returned. If the value does not fit into an int the
// function panics with an out of range error.
func (p *Properties) GetInt(key string, def int) int {
	v, err := p.getInt64(key)
	if err != nil {
		return def
	}
	return intRangeCheck(key, v)
}
```

more: https://github.com/magiconair/properties/blob/c9a06e8f8f0164e4e16c0d5c4793cbed4ac90264/rangecheck.go#L19

**Comment by magiconair** [comment]
I agree, however that would also be a breaking change. I think what is missing are the GetInt32 and GetUint32 methods which don't panic. Can you submit a PR?

**Comment by magiconair** [comment]
I'll create a PR
